apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-flask-app
  namespace: devops-showcase
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-flask-app
  template:
    metadata:
      labels:
        app: devops-flask-app
    spec:
      containers:
      - name: flask-container
        image: perpetuaeayogu/devops-flask-app:latest
        ports:
        - containerPort: 5000

