apiVersion: v1
kind: Service
metadata:
  name: devops-flask-service
  namespace: devops-showcase
spec:
  type: NodePort
  selector:
    app: devops-flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30007

