name: Build and Deploy Code-Server

on:
  push:
    branches:
      - code-server-aws-deploy

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Login to AWS ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build Docker image
      run: |
        docker build -t code-server-app .
        docker tag code-server-app:latest ${{ secrets.ECR_REPOSITORY }}:latest

    - name: Push to ECR
      run: |
        docker push ${{ secrets.ECR_REPOSITORY }}:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
    - name: SSH to EC2 and pull Docker image
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_PUBLIC_IP }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker pull ${{ secrets.ECR_REPOSITORY }}:latest
          docker stop code-server || true
          docker rm code-server || true
          docker run -d --name code-server -p 8080:8080 ${{ secrets.ECR_REPOSITORY }}:latest
