name: CI/CD - Code Server AWS Deploy

on:
  push:
    branches:
      - code-server-aws-deploy   # Only run this pipeline on your portfolio branch
  workflow_dispatch:             # Allow manual trigger

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Build Docker image
      - name: Build Docker image
        run: |
          docker build -t code-server-app ./code-server-deploy

      # 4. Save Docker image as tar for transfer
      - name: Save Docker image
        run: |
          docker save code-server-app -o code-server-app.tar

      # 5. Copy Docker image tar to EC2
      - name: Copy image to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "code-server-app.tar"
          target: "/home/${{ secrets.EC2_USER }}/code-server-app.tar"

      # 6. SSH into EC2 and run container
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker load -i code-server-app.tar
            docker stop code-server || true
            docker rm code-server || true
            docker run -d --name code-server -p 8080:8080 code-server-app
